[package]
name = "rust_plug_wasm2_sdk"
version = "0.1.0"
edition = "2021"

[lib]

[dependencies]
simple-error = "0.2"
gjson = "0.8"
serde = {version = "1.0.136", features = ["derive"] } 
serde_json = "1.0.79"